package com.deltadental.platform.elastic.entity;



public class PlanDetails {

	private String ACK_ID;
	private String FORM_PLAN_YEAR_BEGIN_DATE;
	private String FORM_TAX_PRD;
	private String TYPE_PLAN_ENTITY_CD;
	private String TYPE_DFE_PLAN_ENTITY_CD;
	private String INITIAL_FILING_IND;
	private String AMENDED_IND;
	private String FINAL_FILING_IND;
	private String SHORT_PLAN_YR_IND;
	private String COLLECTIVE_BARGAIN_IND;
	private String F5558_APPLICATION_FILED_IND;
	private String EXT_AUTOMATIC_IND;
	private String DFVC_PROGRAM_IND;
	private String EXT_SPECIAL_IND;
	private String EXT_SPECIAL_TEXT;
	private String PLAN_NAME;
	private String SPONS_DFE_PN;
	private String PLAN_EFF_DATE;
	private String SPONSOR_DFE_NAME;
	private String SPONS_DFE_DBA_NAME;
	private String SPONS_DFE_CARE_OF_NAME;
	private String SPONS_DFE_MAIL_US_ADDRESS1;
	private String SPONS_DFE_MAIL_US_ADDRESS2;
	private String SPONS_DFE_MAIL_US_CITY;
	private String SPONS_DFE_MAIL_US_STATE;
	private String SPONS_DFE_MAIL_US_ZIP;
	private String SPONS_DFE_MAIL_FOREIGN_ADDR1;
	private String SPONS_DFE_MAIL_FOREIGN_ADDR2;
	private String SPONS_DFE_MAIL_FOREIGN_CITY;
	private String SPONS_DFE_MAIL_FORGN_PROV_ST;
	private String SPONS_DFE_MAIL_FOREIGN_CNTRY;
	private String SPONS_DFE_MAIL_FORGN_POSTAL_CD;
	private String SPONS_DFE_LOC_US_ADDRESS1;
	private String SPONS_DFE_LOC_US_ADDRESS2;
	private String SPONS_DFE_LOC_US_CITY;
	private String SPONS_DFE_LOC_US_STATE;
	private String SPONS_DFE_LOC_US_ZIP;
	private String SPONS_DFE_LOC_FOREIGN_ADDRESS1;
	private String SPONS_DFE_LOC_FOREIGN_ADDRESS2;
	private String SPONS_DFE_LOC_FOREIGN_CITY;
	private String SPONS_DFE_LOC_FORGN_PROV_ST;
	private String SPONS_DFE_LOC_FOREIGN_CNTRY;
	private String SPONS_DFE_LOC_FORGN_POSTAL_CD;
	private String SPONS_DFE_EIN;
	private String SPONS_DFE_PHONE_NUM;
	private String BUSINESS_CODE;
	private String ADMIN_NAME;
	private String ADMIN_CARE_OF_NAME;
	private String ADMIN_US_ADDRESS1;
	private String ADMIN_US_ADDRESS2;
	private String ADMIN_US_CITY;
	private String ADMIN_US_STATE;
	private String ADMIN_US_ZIP;
	private String ADMIN_FOREIGN_ADDRESS1;
	private String ADMIN_FOREIGN_ADDRESS2;
	private String ADMIN_FOREIGN_CITY;
	private String ADMIN_FOREIGN_PROV_STATE;
	private String ADMIN_FOREIGN_CNTRY;
	private String ADMIN_FOREIGN_POSTAL_CD;
	private String ADMIN_EIN;
	private String ADMIN_PHONE_NUM;
	private String LAST_RPT_SPONS_NAME;
	private String LAST_RPT_SPONS_EIN;
	private String LAST_RPT_PLAN_NUM;
	private String ADMIN_SIGNED_DATE;
	private String ADMIN_SIGNED_NAME;
	private String SPONS_SIGNED_DATE;
	private String SPONS_SIGNED_NAME;
	private String DFE_SIGNED_DATE;
	private String DFE_SIGNED_NAME;
	private String TOT_PARTCP_BOY_CNT;
	private String TOT_ACTIVE_PARTCP_CNT;
	private String RTD_SEP_PARTCP_RCVG_CNT;
	private String RTD_SEP_PARTCP_FUT_CNT;
	private String SUBTL_ACT_RTD_SEP_CNT;
	private String BENEF_RCVG_BNFT_CNT;
	private String TOT_ACT_RTD_SEP_BENEF_CNT;
	private String PARTCP_ACCOUNT_BAL_CNT;
	private String SEP_PARTCP_PARTL_VSTD_CNT;
	private String CONTRIB_EMPLRS_CNT;
	private String TYPE_PENSION_BNFT_CODE;
	private String TYPE_WELFARE_BNFT_CODE;
	private String FUNDING_INSURANCE_IND;
	private String FUNDING_SEC412_IND;
	private String FUNDING_TRUST_IND;
	private String FUNDING_GEN_ASSET_IND;
	private String BENEFIT_INSURANCE_IND;
	private String BENEFIT_SEC412_IND;
	private String BENEFIT_TRUST_IND;
	private String BENEFIT_GEN_ASSET_IND;
	private String SCH_R_ATTACHED_IND;
	private String SCH_MB_ATTACHED_IND;
	private String SCH_SB_ATTACHED_IND;
	private String SCH_H_ATTACHED_IND;
	private String SCH_I_ATTACHED_IND;
	private String SCH_A_ATTACHED_IND;
	private String NUM_SCH_A_ATTACHED_CNT;
	private String SCH_C_ATTACHED_IND;
	private String SCH_D_ATTACHED_IND;
	private String SCH_G_ATTACHED_IND;
	private String FILING_STATUS;
	private String DATE_RECEIVED;
	private String VALID_ADMIN_SIGNATURE;
	private String VALID_DFE_SIGNATURE;
	private String VALID_SPONSOR_SIGNATURE;
	private String ADMIN_PHONE_NUM_FOREIGN;
	private String SPONS_DFE_PHONE_NUM_FOREIGN;
	private String ADMIN_NAME_SAME_SPON_IND;
	private String ADMIN_ADDRESS_SAME_SPON_IND;
	private String PREPARER_NAME;
	private String PREPARER_FIRM_NAME;
	private String PREPARER_US_ADDRESS1;
	private String PREPARER_US_ADDRESS2;
	private String PREPARER_US_CITY;
	private String PREPARER_US_STATE;
	private String PREPARER_US_ZIP;
	private String PREPARER_FOREIGN_ADDRESS1;
	private String PREPARER_FOREIGN_ADDRESS2;
	private String PREPARER_FOREIGN_CITY;
	private String PREPARER_FOREIGN_PROV_STATE;
	private String PREPARER_FOREIGN_CNTRY;
	private String PREPARER_FOREIGN_POSTAL_CD;
	private String PREPARER_PHONE_NUM;
	private String PREPARER_PHONE_NUM_FOREIGN;
	private String TOT_ACT_PARTCP_BOY_CNT;
	private String SUBJ_M1_FILING_REQ_IND;
	private String COMPLIANCE_M1_FILING_REQ_IND;
	private String M1_RECEIPT_CONFIRMATION_CODE;
	private String ADMIN_MANUAL_SIGNED_DATE;
	private String ADMIN_MANUAL_SIGNED_NAME;
	private String LAST_RPT_PLAN_NAME;
	private String SPONS_MANUAL_SIGNED_DATE;
	private String SPONS_MANUAL_SIGNED_NAME;
	private String DFE_MANUAL_SIGNED_DATE;
	private String DFE_MANUAL_SIGNED_NAME;
	public String getACK_ID() {
		return ACK_ID;
	}
	public void setACK_ID(String aCK_ID) {
		ACK_ID = aCK_ID;
	}
	public String getFORM_PLAN_YEAR_BEGIN_DATE() {
		return FORM_PLAN_YEAR_BEGIN_DATE;
	}
	public void setFORM_PLAN_YEAR_BEGIN_DATE(String fORM_PLAN_YEAR_BEGIN_DATE) {
		FORM_PLAN_YEAR_BEGIN_DATE = fORM_PLAN_YEAR_BEGIN_DATE;
	}
	public String getFORM_TAX_PRD() {
		return FORM_TAX_PRD;
	}
	public void setFORM_TAX_PRD(String fORM_TAX_PRD) {
		FORM_TAX_PRD = fORM_TAX_PRD;
	}
	public String getTYPE_PLAN_ENTITY_CD() {
		return TYPE_PLAN_ENTITY_CD;
	}
	public void setTYPE_PLAN_ENTITY_CD(String tYPE_PLAN_ENTITY_CD) {
		TYPE_PLAN_ENTITY_CD = tYPE_PLAN_ENTITY_CD;
	}
	public String getTYPE_DFE_PLAN_ENTITY_CD() {
		return TYPE_DFE_PLAN_ENTITY_CD;
	}
	public void setTYPE_DFE_PLAN_ENTITY_CD(String tYPE_DFE_PLAN_ENTITY_CD) {
		TYPE_DFE_PLAN_ENTITY_CD = tYPE_DFE_PLAN_ENTITY_CD;
	}
	public String getINITIAL_FILING_IND() {
		return INITIAL_FILING_IND;
	}
	public void setINITIAL_FILING_IND(String iNITIAL_FILING_IND) {
		INITIAL_FILING_IND = iNITIAL_FILING_IND;
	}
	public String getAMENDED_IND() {
		return AMENDED_IND;
	}
	public void setAMENDED_IND(String aMENDED_IND) {
		AMENDED_IND = aMENDED_IND;
	}
	public String getFINAL_FILING_IND() {
		return FINAL_FILING_IND;
	}
	public void setFINAL_FILING_IND(String fINAL_FILING_IND) {
		FINAL_FILING_IND = fINAL_FILING_IND;
	}
	public String getSHORT_PLAN_YR_IND() {
		return SHORT_PLAN_YR_IND;
	}
	public void setSHORT_PLAN_YR_IND(String sHORT_PLAN_YR_IND) {
		SHORT_PLAN_YR_IND = sHORT_PLAN_YR_IND;
	}
	public String getCOLLECTIVE_BARGAIN_IND() {
		return COLLECTIVE_BARGAIN_IND;
	}
	public void setCOLLECTIVE_BARGAIN_IND(String cOLLECTIVE_BARGAIN_IND) {
		COLLECTIVE_BARGAIN_IND = cOLLECTIVE_BARGAIN_IND;
	}
	public String getF5558_APPLICATION_FILED_IND() {
		return F5558_APPLICATION_FILED_IND;
	}
	public void setF5558_APPLICATION_FILED_IND(String f5558_APPLICATION_FILED_IND) {
		F5558_APPLICATION_FILED_IND = f5558_APPLICATION_FILED_IND;
	}
	public String getEXT_AUTOMATIC_IND() {
		return EXT_AUTOMATIC_IND;
	}
	public void setEXT_AUTOMATIC_IND(String eXT_AUTOMATIC_IND) {
		EXT_AUTOMATIC_IND = eXT_AUTOMATIC_IND;
	}
	public String getDFVC_PROGRAM_IND() {
		return DFVC_PROGRAM_IND;
	}
	public void setDFVC_PROGRAM_IND(String dFVC_PROGRAM_IND) {
		DFVC_PROGRAM_IND = dFVC_PROGRAM_IND;
	}
	public String getEXT_SPECIAL_IND() {
		return EXT_SPECIAL_IND;
	}
	public void setEXT_SPECIAL_IND(String eXT_SPECIAL_IND) {
		EXT_SPECIAL_IND = eXT_SPECIAL_IND;
	}
	public String getEXT_SPECIAL_TEXT() {
		return EXT_SPECIAL_TEXT;
	}
	public void setEXT_SPECIAL_TEXT(String eXT_SPECIAL_TEXT) {
		EXT_SPECIAL_TEXT = eXT_SPECIAL_TEXT;
	}
	public String getPLAN_NAME() {
		return PLAN_NAME;
	}
	public void setPLAN_NAME(String pLAN_NAME) {
		PLAN_NAME = pLAN_NAME;
	}
	public String getSPONS_DFE_PN() {
		return SPONS_DFE_PN;
	}
	public void setSPONS_DFE_PN(String sPONS_DFE_PN) {
		SPONS_DFE_PN = sPONS_DFE_PN;
	}
	public String getPLAN_EFF_DATE() {
		return PLAN_EFF_DATE;
	}
	public void setPLAN_EFF_DATE(String pLAN_EFF_DATE) {
		PLAN_EFF_DATE = pLAN_EFF_DATE;
	}
	public String getSPONSOR_DFE_NAME() {
		return SPONSOR_DFE_NAME;
	}
	public void setSPONSOR_DFE_NAME(String sPONSOR_DFE_NAME) {
		SPONSOR_DFE_NAME = sPONSOR_DFE_NAME;
	}
	public String getSPONS_DFE_DBA_NAME() {
		return SPONS_DFE_DBA_NAME;
	}
	public void setSPONS_DFE_DBA_NAME(String sPONS_DFE_DBA_NAME) {
		SPONS_DFE_DBA_NAME = sPONS_DFE_DBA_NAME;
	}
	public String getSPONS_DFE_CARE_OF_NAME() {
		return SPONS_DFE_CARE_OF_NAME;
	}
	public void setSPONS_DFE_CARE_OF_NAME(String sPONS_DFE_CARE_OF_NAME) {
		SPONS_DFE_CARE_OF_NAME = sPONS_DFE_CARE_OF_NAME;
	}
	public String getSPONS_DFE_MAIL_US_ADDRESS1() {
		return SPONS_DFE_MAIL_US_ADDRESS1;
	}
	public void setSPONS_DFE_MAIL_US_ADDRESS1(String sPONS_DFE_MAIL_US_ADDRESS1) {
		SPONS_DFE_MAIL_US_ADDRESS1 = sPONS_DFE_MAIL_US_ADDRESS1;
	}
	public String getSPONS_DFE_MAIL_US_ADDRESS2() {
		return SPONS_DFE_MAIL_US_ADDRESS2;
	}
	public void setSPONS_DFE_MAIL_US_ADDRESS2(String sPONS_DFE_MAIL_US_ADDRESS2) {
		SPONS_DFE_MAIL_US_ADDRESS2 = sPONS_DFE_MAIL_US_ADDRESS2;
	}
	public String getSPONS_DFE_MAIL_US_CITY() {
		return SPONS_DFE_MAIL_US_CITY;
	}
	public void setSPONS_DFE_MAIL_US_CITY(String sPONS_DFE_MAIL_US_CITY) {
		SPONS_DFE_MAIL_US_CITY = sPONS_DFE_MAIL_US_CITY;
	}
	public String getSPONS_DFE_MAIL_US_STATE() {
		return SPONS_DFE_MAIL_US_STATE;
	}
	public void setSPONS_DFE_MAIL_US_STATE(String sPONS_DFE_MAIL_US_STATE) {
		SPONS_DFE_MAIL_US_STATE = sPONS_DFE_MAIL_US_STATE;
	}
	public String getSPONS_DFE_MAIL_US_ZIP() {
		return SPONS_DFE_MAIL_US_ZIP;
	}
	public void setSPONS_DFE_MAIL_US_ZIP(String sPONS_DFE_MAIL_US_ZIP) {
		SPONS_DFE_MAIL_US_ZIP = sPONS_DFE_MAIL_US_ZIP;
	}
	public String getSPONS_DFE_MAIL_FOREIGN_ADDR1() {
		return SPONS_DFE_MAIL_FOREIGN_ADDR1;
	}
	public void setSPONS_DFE_MAIL_FOREIGN_ADDR1(String sPONS_DFE_MAIL_FOREIGN_ADDR1) {
		SPONS_DFE_MAIL_FOREIGN_ADDR1 = sPONS_DFE_MAIL_FOREIGN_ADDR1;
	}
	public String getSPONS_DFE_MAIL_FOREIGN_ADDR2() {
		return SPONS_DFE_MAIL_FOREIGN_ADDR2;
	}
	public void setSPONS_DFE_MAIL_FOREIGN_ADDR2(String sPONS_DFE_MAIL_FOREIGN_ADDR2) {
		SPONS_DFE_MAIL_FOREIGN_ADDR2 = sPONS_DFE_MAIL_FOREIGN_ADDR2;
	}
	public String getSPONS_DFE_MAIL_FOREIGN_CITY() {
		return SPONS_DFE_MAIL_FOREIGN_CITY;
	}
	public void setSPONS_DFE_MAIL_FOREIGN_CITY(String sPONS_DFE_MAIL_FOREIGN_CITY) {
		SPONS_DFE_MAIL_FOREIGN_CITY = sPONS_DFE_MAIL_FOREIGN_CITY;
	}
	public String getSPONS_DFE_MAIL_FORGN_PROV_ST() {
		return SPONS_DFE_MAIL_FORGN_PROV_ST;
	}
	public void setSPONS_DFE_MAIL_FORGN_PROV_ST(String sPONS_DFE_MAIL_FORGN_PROV_ST) {
		SPONS_DFE_MAIL_FORGN_PROV_ST = sPONS_DFE_MAIL_FORGN_PROV_ST;
	}
	public String getSPONS_DFE_MAIL_FOREIGN_CNTRY() {
		return SPONS_DFE_MAIL_FOREIGN_CNTRY;
	}
	public void setSPONS_DFE_MAIL_FOREIGN_CNTRY(String sPONS_DFE_MAIL_FOREIGN_CNTRY) {
		SPONS_DFE_MAIL_FOREIGN_CNTRY = sPONS_DFE_MAIL_FOREIGN_CNTRY;
	}
	public String getSPONS_DFE_MAIL_FORGN_POSTAL_CD() {
		return SPONS_DFE_MAIL_FORGN_POSTAL_CD;
	}
	public void setSPONS_DFE_MAIL_FORGN_POSTAL_CD(String sPONS_DFE_MAIL_FORGN_POSTAL_CD) {
		SPONS_DFE_MAIL_FORGN_POSTAL_CD = sPONS_DFE_MAIL_FORGN_POSTAL_CD;
	}
	public String getSPONS_DFE_LOC_US_ADDRESS1() {
		return SPONS_DFE_LOC_US_ADDRESS1;
	}
	public void setSPONS_DFE_LOC_US_ADDRESS1(String sPONS_DFE_LOC_US_ADDRESS1) {
		SPONS_DFE_LOC_US_ADDRESS1 = sPONS_DFE_LOC_US_ADDRESS1;
	}
	public String getSPONS_DFE_LOC_US_ADDRESS2() {
		return SPONS_DFE_LOC_US_ADDRESS2;
	}
	public void setSPONS_DFE_LOC_US_ADDRESS2(String sPONS_DFE_LOC_US_ADDRESS2) {
		SPONS_DFE_LOC_US_ADDRESS2 = sPONS_DFE_LOC_US_ADDRESS2;
	}
	public String getSPONS_DFE_LOC_US_CITY() {
		return SPONS_DFE_LOC_US_CITY;
	}
	public void setSPONS_DFE_LOC_US_CITY(String sPONS_DFE_LOC_US_CITY) {
		SPONS_DFE_LOC_US_CITY = sPONS_DFE_LOC_US_CITY;
	}
	public String getSPONS_DFE_LOC_US_STATE() {
		return SPONS_DFE_LOC_US_STATE;
	}
	public void setSPONS_DFE_LOC_US_STATE(String sPONS_DFE_LOC_US_STATE) {
		SPONS_DFE_LOC_US_STATE = sPONS_DFE_LOC_US_STATE;
	}
	public String getSPONS_DFE_LOC_US_ZIP() {
		return SPONS_DFE_LOC_US_ZIP;
	}
	public void setSPONS_DFE_LOC_US_ZIP(String sPONS_DFE_LOC_US_ZIP) {
		SPONS_DFE_LOC_US_ZIP = sPONS_DFE_LOC_US_ZIP;
	}
	public String getSPONS_DFE_LOC_FOREIGN_ADDRESS1() {
		return SPONS_DFE_LOC_FOREIGN_ADDRESS1;
	}
	public void setSPONS_DFE_LOC_FOREIGN_ADDRESS1(String sPONS_DFE_LOC_FOREIGN_ADDRESS1) {
		SPONS_DFE_LOC_FOREIGN_ADDRESS1 = sPONS_DFE_LOC_FOREIGN_ADDRESS1;
	}
	public String getSPONS_DFE_LOC_FOREIGN_ADDRESS2() {
		return SPONS_DFE_LOC_FOREIGN_ADDRESS2;
	}
	public void setSPONS_DFE_LOC_FOREIGN_ADDRESS2(String sPONS_DFE_LOC_FOREIGN_ADDRESS2) {
		SPONS_DFE_LOC_FOREIGN_ADDRESS2 = sPONS_DFE_LOC_FOREIGN_ADDRESS2;
	}
	public String getSPONS_DFE_LOC_FOREIGN_CITY() {
		return SPONS_DFE_LOC_FOREIGN_CITY;
	}
	public void setSPONS_DFE_LOC_FOREIGN_CITY(String sPONS_DFE_LOC_FOREIGN_CITY) {
		SPONS_DFE_LOC_FOREIGN_CITY = sPONS_DFE_LOC_FOREIGN_CITY;
	}
	public String getSPONS_DFE_LOC_FORGN_PROV_ST() {
		return SPONS_DFE_LOC_FORGN_PROV_ST;
	}
	public void setSPONS_DFE_LOC_FORGN_PROV_ST(String sPONS_DFE_LOC_FORGN_PROV_ST) {
		SPONS_DFE_LOC_FORGN_PROV_ST = sPONS_DFE_LOC_FORGN_PROV_ST;
	}
	public String getSPONS_DFE_LOC_FOREIGN_CNTRY() {
		return SPONS_DFE_LOC_FOREIGN_CNTRY;
	}
	public void setSPONS_DFE_LOC_FOREIGN_CNTRY(String sPONS_DFE_LOC_FOREIGN_CNTRY) {
		SPONS_DFE_LOC_FOREIGN_CNTRY = sPONS_DFE_LOC_FOREIGN_CNTRY;
	}
	public String getSPONS_DFE_LOC_FORGN_POSTAL_CD() {
		return SPONS_DFE_LOC_FORGN_POSTAL_CD;
	}
	public void setSPONS_DFE_LOC_FORGN_POSTAL_CD(String sPONS_DFE_LOC_FORGN_POSTAL_CD) {
		SPONS_DFE_LOC_FORGN_POSTAL_CD = sPONS_DFE_LOC_FORGN_POSTAL_CD;
	}
	public String getSPONS_DFE_EIN() {
		return SPONS_DFE_EIN;
	}
	public void setSPONS_DFE_EIN(String sPONS_DFE_EIN) {
		SPONS_DFE_EIN = sPONS_DFE_EIN;
	}
	public String getSPONS_DFE_PHONE_NUM() {
		return SPONS_DFE_PHONE_NUM;
	}
	public void setSPONS_DFE_PHONE_NUM(String sPONS_DFE_PHONE_NUM) {
		SPONS_DFE_PHONE_NUM = sPONS_DFE_PHONE_NUM;
	}
	public String getBUSINESS_CODE() {
		return BUSINESS_CODE;
	}
	public void setBUSINESS_CODE(String bUSINESS_CODE) {
		BUSINESS_CODE = bUSINESS_CODE;
	}
	public String getADMIN_NAME() {
		return ADMIN_NAME;
	}
	public void setADMIN_NAME(String aDMIN_NAME) {
		ADMIN_NAME = aDMIN_NAME;
	}
	public String getADMIN_CARE_OF_NAME() {
		return ADMIN_CARE_OF_NAME;
	}
	public void setADMIN_CARE_OF_NAME(String aDMIN_CARE_OF_NAME) {
		ADMIN_CARE_OF_NAME = aDMIN_CARE_OF_NAME;
	}
	public String getADMIN_US_ADDRESS1() {
		return ADMIN_US_ADDRESS1;
	}
	public void setADMIN_US_ADDRESS1(String aDMIN_US_ADDRESS1) {
		ADMIN_US_ADDRESS1 = aDMIN_US_ADDRESS1;
	}
	public String getADMIN_US_ADDRESS2() {
		return ADMIN_US_ADDRESS2;
	}
	public void setADMIN_US_ADDRESS2(String aDMIN_US_ADDRESS2) {
		ADMIN_US_ADDRESS2 = aDMIN_US_ADDRESS2;
	}
	public String getADMIN_US_CITY() {
		return ADMIN_US_CITY;
	}
	public void setADMIN_US_CITY(String aDMIN_US_CITY) {
		ADMIN_US_CITY = aDMIN_US_CITY;
	}
	public String getADMIN_US_STATE() {
		return ADMIN_US_STATE;
	}
	public void setADMIN_US_STATE(String aDMIN_US_STATE) {
		ADMIN_US_STATE = aDMIN_US_STATE;
	}
	public String getADMIN_US_ZIP() {
		return ADMIN_US_ZIP;
	}
	public void setADMIN_US_ZIP(String aDMIN_US_ZIP) {
		ADMIN_US_ZIP = aDMIN_US_ZIP;
	}
	public String getADMIN_FOREIGN_ADDRESS1() {
		return ADMIN_FOREIGN_ADDRESS1;
	}
	public void setADMIN_FOREIGN_ADDRESS1(String aDMIN_FOREIGN_ADDRESS1) {
		ADMIN_FOREIGN_ADDRESS1 = aDMIN_FOREIGN_ADDRESS1;
	}
	public String getADMIN_FOREIGN_ADDRESS2() {
		return ADMIN_FOREIGN_ADDRESS2;
	}
	public void setADMIN_FOREIGN_ADDRESS2(String aDMIN_FOREIGN_ADDRESS2) {
		ADMIN_FOREIGN_ADDRESS2 = aDMIN_FOREIGN_ADDRESS2;
	}
	public String getADMIN_FOREIGN_CITY() {
		return ADMIN_FOREIGN_CITY;
	}
	public void setADMIN_FOREIGN_CITY(String aDMIN_FOREIGN_CITY) {
		ADMIN_FOREIGN_CITY = aDMIN_FOREIGN_CITY;
	}
	public String getADMIN_FOREIGN_PROV_STATE() {
		return ADMIN_FOREIGN_PROV_STATE;
	}
	public void setADMIN_FOREIGN_PROV_STATE(String aDMIN_FOREIGN_PROV_STATE) {
		ADMIN_FOREIGN_PROV_STATE = aDMIN_FOREIGN_PROV_STATE;
	}
	public String getADMIN_FOREIGN_CNTRY() {
		return ADMIN_FOREIGN_CNTRY;
	}
	public void setADMIN_FOREIGN_CNTRY(String aDMIN_FOREIGN_CNTRY) {
		ADMIN_FOREIGN_CNTRY = aDMIN_FOREIGN_CNTRY;
	}
	public String getADMIN_FOREIGN_POSTAL_CD() {
		return ADMIN_FOREIGN_POSTAL_CD;
	}
	public void setADMIN_FOREIGN_POSTAL_CD(String aDMIN_FOREIGN_POSTAL_CD) {
		ADMIN_FOREIGN_POSTAL_CD = aDMIN_FOREIGN_POSTAL_CD;
	}
	public String getADMIN_EIN() {
		return ADMIN_EIN;
	}
	public void setADMIN_EIN(String aDMIN_EIN) {
		ADMIN_EIN = aDMIN_EIN;
	}
	public String getADMIN_PHONE_NUM() {
		return ADMIN_PHONE_NUM;
	}
	public void setADMIN_PHONE_NUM(String aDMIN_PHONE_NUM) {
		ADMIN_PHONE_NUM = aDMIN_PHONE_NUM;
	}
	public String getLAST_RPT_SPONS_NAME() {
		return LAST_RPT_SPONS_NAME;
	}
	public void setLAST_RPT_SPONS_NAME(String lAST_RPT_SPONS_NAME) {
		LAST_RPT_SPONS_NAME = lAST_RPT_SPONS_NAME;
	}
	public String getLAST_RPT_SPONS_EIN() {
		return LAST_RPT_SPONS_EIN;
	}
	public void setLAST_RPT_SPONS_EIN(String lAST_RPT_SPONS_EIN) {
		LAST_RPT_SPONS_EIN = lAST_RPT_SPONS_EIN;
	}
	public String getLAST_RPT_PLAN_NUM() {
		return LAST_RPT_PLAN_NUM;
	}
	public void setLAST_RPT_PLAN_NUM(String lAST_RPT_PLAN_NUM) {
		LAST_RPT_PLAN_NUM = lAST_RPT_PLAN_NUM;
	}
	public String getADMIN_SIGNED_DATE() {
		return ADMIN_SIGNED_DATE;
	}
	public void setADMIN_SIGNED_DATE(String aDMIN_SIGNED_DATE) {
		ADMIN_SIGNED_DATE = aDMIN_SIGNED_DATE;
	}
	public String getADMIN_SIGNED_NAME() {
		return ADMIN_SIGNED_NAME;
	}
	public void setADMIN_SIGNED_NAME(String aDMIN_SIGNED_NAME) {
		ADMIN_SIGNED_NAME = aDMIN_SIGNED_NAME;
	}
	public String getSPONS_SIGNED_DATE() {
		return SPONS_SIGNED_DATE;
	}
	public void setSPONS_SIGNED_DATE(String sPONS_SIGNED_DATE) {
		SPONS_SIGNED_DATE = sPONS_SIGNED_DATE;
	}
	public String getSPONS_SIGNED_NAME() {
		return SPONS_SIGNED_NAME;
	}
	public void setSPONS_SIGNED_NAME(String sPONS_SIGNED_NAME) {
		SPONS_SIGNED_NAME = sPONS_SIGNED_NAME;
	}
	public String getDFE_SIGNED_DATE() {
		return DFE_SIGNED_DATE;
	}
	public void setDFE_SIGNED_DATE(String dFE_SIGNED_DATE) {
		DFE_SIGNED_DATE = dFE_SIGNED_DATE;
	}
	public String getDFE_SIGNED_NAME() {
		return DFE_SIGNED_NAME;
	}
	public void setDFE_SIGNED_NAME(String dFE_SIGNED_NAME) {
		DFE_SIGNED_NAME = dFE_SIGNED_NAME;
	}
	public String getTOT_PARTCP_BOY_CNT() {
		return TOT_PARTCP_BOY_CNT;
	}
	public void setTOT_PARTCP_BOY_CNT(String tOT_PARTCP_BOY_CNT) {
		TOT_PARTCP_BOY_CNT = tOT_PARTCP_BOY_CNT;
	}
	public String getTOT_ACTIVE_PARTCP_CNT() {
		return TOT_ACTIVE_PARTCP_CNT;
	}
	public void setTOT_ACTIVE_PARTCP_CNT(String tOT_ACTIVE_PARTCP_CNT) {
		TOT_ACTIVE_PARTCP_CNT = tOT_ACTIVE_PARTCP_CNT;
	}
	public String getRTD_SEP_PARTCP_RCVG_CNT() {
		return RTD_SEP_PARTCP_RCVG_CNT;
	}
	public void setRTD_SEP_PARTCP_RCVG_CNT(String rTD_SEP_PARTCP_RCVG_CNT) {
		RTD_SEP_PARTCP_RCVG_CNT = rTD_SEP_PARTCP_RCVG_CNT;
	}
	public String getRTD_SEP_PARTCP_FUT_CNT() {
		return RTD_SEP_PARTCP_FUT_CNT;
	}
	public void setRTD_SEP_PARTCP_FUT_CNT(String rTD_SEP_PARTCP_FUT_CNT) {
		RTD_SEP_PARTCP_FUT_CNT = rTD_SEP_PARTCP_FUT_CNT;
	}
	public String getSUBTL_ACT_RTD_SEP_CNT() {
		return SUBTL_ACT_RTD_SEP_CNT;
	}
	public void setSUBTL_ACT_RTD_SEP_CNT(String sUBTL_ACT_RTD_SEP_CNT) {
		SUBTL_ACT_RTD_SEP_CNT = sUBTL_ACT_RTD_SEP_CNT;
	}
	public String getBENEF_RCVG_BNFT_CNT() {
		return BENEF_RCVG_BNFT_CNT;
	}
	public void setBENEF_RCVG_BNFT_CNT(String bENEF_RCVG_BNFT_CNT) {
		BENEF_RCVG_BNFT_CNT = bENEF_RCVG_BNFT_CNT;
	}
	public String getTOT_ACT_RTD_SEP_BENEF_CNT() {
		return TOT_ACT_RTD_SEP_BENEF_CNT;
	}
	public void setTOT_ACT_RTD_SEP_BENEF_CNT(String tOT_ACT_RTD_SEP_BENEF_CNT) {
		TOT_ACT_RTD_SEP_BENEF_CNT = tOT_ACT_RTD_SEP_BENEF_CNT;
	}
	public String getPARTCP_ACCOUNT_BAL_CNT() {
		return PARTCP_ACCOUNT_BAL_CNT;
	}
	public void setPARTCP_ACCOUNT_BAL_CNT(String pARTCP_ACCOUNT_BAL_CNT) {
		PARTCP_ACCOUNT_BAL_CNT = pARTCP_ACCOUNT_BAL_CNT;
	}
	public String getSEP_PARTCP_PARTL_VSTD_CNT() {
		return SEP_PARTCP_PARTL_VSTD_CNT;
	}
	public void setSEP_PARTCP_PARTL_VSTD_CNT(String sEP_PARTCP_PARTL_VSTD_CNT) {
		SEP_PARTCP_PARTL_VSTD_CNT = sEP_PARTCP_PARTL_VSTD_CNT;
	}
	public String getCONTRIB_EMPLRS_CNT() {
		return CONTRIB_EMPLRS_CNT;
	}
	public void setCONTRIB_EMPLRS_CNT(String cONTRIB_EMPLRS_CNT) {
		CONTRIB_EMPLRS_CNT = cONTRIB_EMPLRS_CNT;
	}
	public String getTYPE_PENSION_BNFT_CODE() {
		return TYPE_PENSION_BNFT_CODE;
	}
	public void setTYPE_PENSION_BNFT_CODE(String tYPE_PENSION_BNFT_CODE) {
		TYPE_PENSION_BNFT_CODE = tYPE_PENSION_BNFT_CODE;
	}
	public String getTYPE_WELFARE_BNFT_CODE() {
		return TYPE_WELFARE_BNFT_CODE;
	}
	public void setTYPE_WELFARE_BNFT_CODE(String tYPE_WELFARE_BNFT_CODE) {
		TYPE_WELFARE_BNFT_CODE = tYPE_WELFARE_BNFT_CODE;
	}
	public String getFUNDING_INSURANCE_IND() {
		return FUNDING_INSURANCE_IND;
	}
	public void setFUNDING_INSURANCE_IND(String fUNDING_INSURANCE_IND) {
		FUNDING_INSURANCE_IND = fUNDING_INSURANCE_IND;
	}
	public String getFUNDING_SEC412_IND() {
		return FUNDING_SEC412_IND;
	}
	public void setFUNDING_SEC412_IND(String fUNDING_SEC412_IND) {
		FUNDING_SEC412_IND = fUNDING_SEC412_IND;
	}
	public String getFUNDING_TRUST_IND() {
		return FUNDING_TRUST_IND;
	}
	public void setFUNDING_TRUST_IND(String fUNDING_TRUST_IND) {
		FUNDING_TRUST_IND = fUNDING_TRUST_IND;
	}
	public String getFUNDING_GEN_ASSET_IND() {
		return FUNDING_GEN_ASSET_IND;
	}
	public void setFUNDING_GEN_ASSET_IND(String fUNDING_GEN_ASSET_IND) {
		FUNDING_GEN_ASSET_IND = fUNDING_GEN_ASSET_IND;
	}
	public String getBENEFIT_INSURANCE_IND() {
		return BENEFIT_INSURANCE_IND;
	}
	public void setBENEFIT_INSURANCE_IND(String bENEFIT_INSURANCE_IND) {
		BENEFIT_INSURANCE_IND = bENEFIT_INSURANCE_IND;
	}
	public String getBENEFIT_SEC412_IND() {
		return BENEFIT_SEC412_IND;
	}
	public void setBENEFIT_SEC412_IND(String bENEFIT_SEC412_IND) {
		BENEFIT_SEC412_IND = bENEFIT_SEC412_IND;
	}
	public String getBENEFIT_TRUST_IND() {
		return BENEFIT_TRUST_IND;
	}
	public void setBENEFIT_TRUST_IND(String bENEFIT_TRUST_IND) {
		BENEFIT_TRUST_IND = bENEFIT_TRUST_IND;
	}
	public String getBENEFIT_GEN_ASSET_IND() {
		return BENEFIT_GEN_ASSET_IND;
	}
	public void setBENEFIT_GEN_ASSET_IND(String bENEFIT_GEN_ASSET_IND) {
		BENEFIT_GEN_ASSET_IND = bENEFIT_GEN_ASSET_IND;
	}
	public String getSCH_R_ATTACHED_IND() {
		return SCH_R_ATTACHED_IND;
	}
	public void setSCH_R_ATTACHED_IND(String sCH_R_ATTACHED_IND) {
		SCH_R_ATTACHED_IND = sCH_R_ATTACHED_IND;
	}
	public String getSCH_MB_ATTACHED_IND() {
		return SCH_MB_ATTACHED_IND;
	}
	public void setSCH_MB_ATTACHED_IND(String sCH_MB_ATTACHED_IND) {
		SCH_MB_ATTACHED_IND = sCH_MB_ATTACHED_IND;
	}
	public String getSCH_SB_ATTACHED_IND() {
		return SCH_SB_ATTACHED_IND;
	}
	public void setSCH_SB_ATTACHED_IND(String sCH_SB_ATTACHED_IND) {
		SCH_SB_ATTACHED_IND = sCH_SB_ATTACHED_IND;
	}
	public String getSCH_H_ATTACHED_IND() {
		return SCH_H_ATTACHED_IND;
	}
	public void setSCH_H_ATTACHED_IND(String sCH_H_ATTACHED_IND) {
		SCH_H_ATTACHED_IND = sCH_H_ATTACHED_IND;
	}
	public String getSCH_I_ATTACHED_IND() {
		return SCH_I_ATTACHED_IND;
	}
	public void setSCH_I_ATTACHED_IND(String sCH_I_ATTACHED_IND) {
		SCH_I_ATTACHED_IND = sCH_I_ATTACHED_IND;
	}
	public String getSCH_A_ATTACHED_IND() {
		return SCH_A_ATTACHED_IND;
	}
	public void setSCH_A_ATTACHED_IND(String sCH_A_ATTACHED_IND) {
		SCH_A_ATTACHED_IND = sCH_A_ATTACHED_IND;
	}
	public String getNUM_SCH_A_ATTACHED_CNT() {
		return NUM_SCH_A_ATTACHED_CNT;
	}
	public void setNUM_SCH_A_ATTACHED_CNT(String nUM_SCH_A_ATTACHED_CNT) {
		NUM_SCH_A_ATTACHED_CNT = nUM_SCH_A_ATTACHED_CNT;
	}
	public String getSCH_C_ATTACHED_IND() {
		return SCH_C_ATTACHED_IND;
	}
	public void setSCH_C_ATTACHED_IND(String sCH_C_ATTACHED_IND) {
		SCH_C_ATTACHED_IND = sCH_C_ATTACHED_IND;
	}
	public String getSCH_D_ATTACHED_IND() {
		return SCH_D_ATTACHED_IND;
	}
	public void setSCH_D_ATTACHED_IND(String sCH_D_ATTACHED_IND) {
		SCH_D_ATTACHED_IND = sCH_D_ATTACHED_IND;
	}
	public String getSCH_G_ATTACHED_IND() {
		return SCH_G_ATTACHED_IND;
	}
	public void setSCH_G_ATTACHED_IND(String sCH_G_ATTACHED_IND) {
		SCH_G_ATTACHED_IND = sCH_G_ATTACHED_IND;
	}
	public String getFILING_STATUS() {
		return FILING_STATUS;
	}
	public void setFILING_STATUS(String fILING_STATUS) {
		FILING_STATUS = fILING_STATUS;
	}
	public String getDATE_RECEIVED() {
		return DATE_RECEIVED;
	}
	public void setDATE_RECEIVED(String dATE_RECEIVED) {
		DATE_RECEIVED = dATE_RECEIVED;
	}
	public String getVALID_ADMIN_SIGNATURE() {
		return VALID_ADMIN_SIGNATURE;
	}
	public void setVALID_ADMIN_SIGNATURE(String vALID_ADMIN_SIGNATURE) {
		VALID_ADMIN_SIGNATURE = vALID_ADMIN_SIGNATURE;
	}
	public String getVALID_DFE_SIGNATURE() {
		return VALID_DFE_SIGNATURE;
	}
	public void setVALID_DFE_SIGNATURE(String vALID_DFE_SIGNATURE) {
		VALID_DFE_SIGNATURE = vALID_DFE_SIGNATURE;
	}
	public String getVALID_SPONSOR_SIGNATURE() {
		return VALID_SPONSOR_SIGNATURE;
	}
	public void setVALID_SPONSOR_SIGNATURE(String vALID_SPONSOR_SIGNATURE) {
		VALID_SPONSOR_SIGNATURE = vALID_SPONSOR_SIGNATURE;
	}
	public String getADMIN_PHONE_NUM_FOREIGN() {
		return ADMIN_PHONE_NUM_FOREIGN;
	}
	public void setADMIN_PHONE_NUM_FOREIGN(String aDMIN_PHONE_NUM_FOREIGN) {
		ADMIN_PHONE_NUM_FOREIGN = aDMIN_PHONE_NUM_FOREIGN;
	}
	public String getSPONS_DFE_PHONE_NUM_FOREIGN() {
		return SPONS_DFE_PHONE_NUM_FOREIGN;
	}
	public void setSPONS_DFE_PHONE_NUM_FOREIGN(String sPONS_DFE_PHONE_NUM_FOREIGN) {
		SPONS_DFE_PHONE_NUM_FOREIGN = sPONS_DFE_PHONE_NUM_FOREIGN;
	}
	public String getADMIN_NAME_SAME_SPON_IND() {
		return ADMIN_NAME_SAME_SPON_IND;
	}
	public void setADMIN_NAME_SAME_SPON_IND(String aDMIN_NAME_SAME_SPON_IND) {
		ADMIN_NAME_SAME_SPON_IND = aDMIN_NAME_SAME_SPON_IND;
	}
	public String getADMIN_ADDRESS_SAME_SPON_IND() {
		return ADMIN_ADDRESS_SAME_SPON_IND;
	}
	public void setADMIN_ADDRESS_SAME_SPON_IND(String aDMIN_ADDRESS_SAME_SPON_IND) {
		ADMIN_ADDRESS_SAME_SPON_IND = aDMIN_ADDRESS_SAME_SPON_IND;
	}
	public String getPREPARER_NAME() {
		return PREPARER_NAME;
	}
	public void setPREPARER_NAME(String pREPARER_NAME) {
		PREPARER_NAME = pREPARER_NAME;
	}
	public String getPREPARER_FIRM_NAME() {
		return PREPARER_FIRM_NAME;
	}
	public void setPREPARER_FIRM_NAME(String pREPARER_FIRM_NAME) {
		PREPARER_FIRM_NAME = pREPARER_FIRM_NAME;
	}
	public String getPREPARER_US_ADDRESS1() {
		return PREPARER_US_ADDRESS1;
	}
	public void setPREPARER_US_ADDRESS1(String pREPARER_US_ADDRESS1) {
		PREPARER_US_ADDRESS1 = pREPARER_US_ADDRESS1;
	}
	public String getPREPARER_US_ADDRESS2() {
		return PREPARER_US_ADDRESS2;
	}
	public void setPREPARER_US_ADDRESS2(String pREPARER_US_ADDRESS2) {
		PREPARER_US_ADDRESS2 = pREPARER_US_ADDRESS2;
	}
	public String getPREPARER_US_CITY() {
		return PREPARER_US_CITY;
	}
	public void setPREPARER_US_CITY(String pREPARER_US_CITY) {
		PREPARER_US_CITY = pREPARER_US_CITY;
	}
	public String getPREPARER_US_STATE() {
		return PREPARER_US_STATE;
	}
	public void setPREPARER_US_STATE(String pREPARER_US_STATE) {
		PREPARER_US_STATE = pREPARER_US_STATE;
	}
	public String getPREPARER_US_ZIP() {
		return PREPARER_US_ZIP;
	}
	public void setPREPARER_US_ZIP(String pREPARER_US_ZIP) {
		PREPARER_US_ZIP = pREPARER_US_ZIP;
	}
	public String getPREPARER_FOREIGN_ADDRESS1() {
		return PREPARER_FOREIGN_ADDRESS1;
	}
	public void setPREPARER_FOREIGN_ADDRESS1(String pREPARER_FOREIGN_ADDRESS1) {
		PREPARER_FOREIGN_ADDRESS1 = pREPARER_FOREIGN_ADDRESS1;
	}
	public String getPREPARER_FOREIGN_ADDRESS2() {
		return PREPARER_FOREIGN_ADDRESS2;
	}
	public void setPREPARER_FOREIGN_ADDRESS2(String pREPARER_FOREIGN_ADDRESS2) {
		PREPARER_FOREIGN_ADDRESS2 = pREPARER_FOREIGN_ADDRESS2;
	}
	public String getPREPARER_FOREIGN_CITY() {
		return PREPARER_FOREIGN_CITY;
	}
	public void setPREPARER_FOREIGN_CITY(String pREPARER_FOREIGN_CITY) {
		PREPARER_FOREIGN_CITY = pREPARER_FOREIGN_CITY;
	}
	public String getPREPARER_FOREIGN_PROV_STATE() {
		return PREPARER_FOREIGN_PROV_STATE;
	}
	public void setPREPARER_FOREIGN_PROV_STATE(String pREPARER_FOREIGN_PROV_STATE) {
		PREPARER_FOREIGN_PROV_STATE = pREPARER_FOREIGN_PROV_STATE;
	}
	public String getPREPARER_FOREIGN_CNTRY() {
		return PREPARER_FOREIGN_CNTRY;
	}
	public void setPREPARER_FOREIGN_CNTRY(String pREPARER_FOREIGN_CNTRY) {
		PREPARER_FOREIGN_CNTRY = pREPARER_FOREIGN_CNTRY;
	}
	public String getPREPARER_FOREIGN_POSTAL_CD() {
		return PREPARER_FOREIGN_POSTAL_CD;
	}
	public void setPREPARER_FOREIGN_POSTAL_CD(String pREPARER_FOREIGN_POSTAL_CD) {
		PREPARER_FOREIGN_POSTAL_CD = pREPARER_FOREIGN_POSTAL_CD;
	}
	public String getPREPARER_PHONE_NUM() {
		return PREPARER_PHONE_NUM;
	}
	public void setPREPARER_PHONE_NUM(String pREPARER_PHONE_NUM) {
		PREPARER_PHONE_NUM = pREPARER_PHONE_NUM;
	}
	public String getPREPARER_PHONE_NUM_FOREIGN() {
		return PREPARER_PHONE_NUM_FOREIGN;
	}
	public void setPREPARER_PHONE_NUM_FOREIGN(String pREPARER_PHONE_NUM_FOREIGN) {
		PREPARER_PHONE_NUM_FOREIGN = pREPARER_PHONE_NUM_FOREIGN;
	}
	public String getTOT_ACT_PARTCP_BOY_CNT() {
		return TOT_ACT_PARTCP_BOY_CNT;
	}
	public void setTOT_ACT_PARTCP_BOY_CNT(String tOT_ACT_PARTCP_BOY_CNT) {
		TOT_ACT_PARTCP_BOY_CNT = tOT_ACT_PARTCP_BOY_CNT;
	}
	public String getSUBJ_M1_FILING_REQ_IND() {
		return SUBJ_M1_FILING_REQ_IND;
	}
	public void setSUBJ_M1_FILING_REQ_IND(String sUBJ_M1_FILING_REQ_IND) {
		SUBJ_M1_FILING_REQ_IND = sUBJ_M1_FILING_REQ_IND;
	}
	public String getCOMPLIANCE_M1_FILING_REQ_IND() {
		return COMPLIANCE_M1_FILING_REQ_IND;
	}
	public void setCOMPLIANCE_M1_FILING_REQ_IND(String cOMPLIANCE_M1_FILING_REQ_IND) {
		COMPLIANCE_M1_FILING_REQ_IND = cOMPLIANCE_M1_FILING_REQ_IND;
	}
	public String getM1_RECEIPT_CONFIRMATION_CODE() {
		return M1_RECEIPT_CONFIRMATION_CODE;
	}
	public void setM1_RECEIPT_CONFIRMATION_CODE(String m1_RECEIPT_CONFIRMATION_CODE) {
		M1_RECEIPT_CONFIRMATION_CODE = m1_RECEIPT_CONFIRMATION_CODE;
	}
	public String getADMIN_MANUAL_SIGNED_DATE() {
		return ADMIN_MANUAL_SIGNED_DATE;
	}
	public void setADMIN_MANUAL_SIGNED_DATE(String aDMIN_MANUAL_SIGNED_DATE) {
		ADMIN_MANUAL_SIGNED_DATE = aDMIN_MANUAL_SIGNED_DATE;
	}
	public String getADMIN_MANUAL_SIGNED_NAME() {
		return ADMIN_MANUAL_SIGNED_NAME;
	}
	public void setADMIN_MANUAL_SIGNED_NAME(String aDMIN_MANUAL_SIGNED_NAME) {
		ADMIN_MANUAL_SIGNED_NAME = aDMIN_MANUAL_SIGNED_NAME;
	}
	public String getLAST_RPT_PLAN_NAME() {
		return LAST_RPT_PLAN_NAME;
	}
	public void setLAST_RPT_PLAN_NAME(String lAST_RPT_PLAN_NAME) {
		LAST_RPT_PLAN_NAME = lAST_RPT_PLAN_NAME;
	}
	public String getSPONS_MANUAL_SIGNED_DATE() {
		return SPONS_MANUAL_SIGNED_DATE;
	}
	public void setSPONS_MANUAL_SIGNED_DATE(String sPONS_MANUAL_SIGNED_DATE) {
		SPONS_MANUAL_SIGNED_DATE = sPONS_MANUAL_SIGNED_DATE;
	}
	public String getSPONS_MANUAL_SIGNED_NAME() {
		return SPONS_MANUAL_SIGNED_NAME;
	}
	public void setSPONS_MANUAL_SIGNED_NAME(String sPONS_MANUAL_SIGNED_NAME) {
		SPONS_MANUAL_SIGNED_NAME = sPONS_MANUAL_SIGNED_NAME;
	}
	public String getDFE_MANUAL_SIGNED_DATE() {
		return DFE_MANUAL_SIGNED_DATE;
	}
	public void setDFE_MANUAL_SIGNED_DATE(String dFE_MANUAL_SIGNED_DATE) {
		DFE_MANUAL_SIGNED_DATE = dFE_MANUAL_SIGNED_DATE;
	}
	public String getDFE_MANUAL_SIGNED_NAME() {
		return DFE_MANUAL_SIGNED_NAME;
	}
	public void setDFE_MANUAL_SIGNED_NAME(String dFE_MANUAL_SIGNED_NAME) {
		DFE_MANUAL_SIGNED_NAME = dFE_MANUAL_SIGNED_NAME;
	}
	
	
}
